### ISSUE TITLE
 org.xml.sax.SAXParseException XML version "1.1" is not supported, only XML 1.0 is supported.

### ISSUE THREAD

**Issue by frogu** [sheehan/job-dsl-gradle-example#102] opened 2018-08-28 16:34 UTC
Hi! 

job-dsl-gradle-example version: master
job-dsl version: 1.70

Starts to fail when upgrading jenkins (harness) version to LTS 2.107.x
Problem disappears when reverting to LTS 2.89.4

If more info/debugging is required I'm happy to provide it.

Best Regards
Łukasz Proszek

```

Expected no exception to be thrown, but got 'javaposse.jobdsl.dsl.DslException'
	at spock.lang.Specification.noExceptionThrown(Specification.java:118)
	at com.dslexample.JobScriptsSpec.test script #file.name(JobScriptsSpec.groovy:47)
Caused by: javaposse.jobdsl.dsl.DslException: Could not read configuration file /tmp/jenkinsTests.tmp/jenkins2252288404978110417test/jobs/restarts/config.xml for job restarts
	at javaposse.jobdsl.plugin.JenkinsJobManagement.checkItemType(JenkinsJobManagement.java:471)
	at javaposse.jobdsl.plugin.JenkinsJobManagement.updateExistingItem(JenkinsJobManagement.java:451)
	at javaposse.jobdsl.plugin.JenkinsJobManagement.createOrUpdateConfig(JenkinsJobManagement.java:139)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.extractGeneratedJobs_closure4(AbstractDslScriptLoader.groovy:194)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.extractGeneratedJobs(AbstractDslScriptLoader.groovy:187)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.extractGeneratedItems(AbstractDslScriptLoader.groovy:174)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts_closure1(AbstractDslScriptLoader.groovy:61)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts(AbstractDslScriptLoader.groovy:46)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScript(AbstractDslScriptLoader.groovy:85)
	at com.dslexample.JobScriptsSpec.test script #file.name(JobScriptsSpec.groovy:43)
Caused by: org.xml.sax.SAXParseException; systemId: file:///tmp/jenkinsTests.tmp/jenkins2252288404978110417test/jobs/restarts/config.xml; lineNumber: 1; columnNumber: 20; XML version "1.1" is not supported, only XML 1.0 is supported.
	at groovy.util.XmlParser.parse(XmlParser.java:193)
	at javaposse.jobdsl.plugin.JenkinsJobManagement.checkItemType(JenkinsJobManagement.java:469)
	... 13 more
```

**Comment by AnalogJ** [comment] 2019-05-21 19:05
This is broken for us as well. Any idea whats going on @sheehan @daspilker ?

**Comment by sheehan** [comment] 2019-05-28 19:04
I'm not able to reproduce. What changes did you make?

**Comment by sheehan** [comment] 2019-08-31 14:12
Closing. Cant reproduce.

**Closed by sheehan** 2019-08-31 14:12 UTC

**Comment by madAndroid** [comment] 2020-05-12 13:31
I managed to "fix" this with this commit: https://github.com/sheehan/job-dsl-gradle-example/commit/2af0cb814906d39fcf874bd5a94bf7df3ed36178
